apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: almahdi-chihaoui/backend
        imagePullPolicy: IfNotPresent
        command: ["npm"]
        args: ["run", "dev"]
        ports:
        - name: http
          containerPort: 3000
        - name: debug
          containerPort: 9229